<?php
$produtos = [
    ["foto" => "fotos/cozinha-verde.jpg", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha-marrom.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha-preto.jpg", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha-preto2.jpg", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha1.jpg", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha2.jpg", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha3.jpg", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha4.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha5.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha6.jpg", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha7.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha8.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha9.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha10.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha11.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha12.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha13.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha14.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha15.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha16.webp", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha17.jpg", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha18.jpg", "categoria" => "cozinha"],
    ["foto" => "fotos/cozinha19.jpg", "categoria" => "cozinha"],


    ["foto" => "fotos/quartoDeCrianca1.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quartoDeCrianca2.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto1.jpg", "categoria" => "quarto"],
    ["foto" => "fotos/quarto2.jpg", "categoria" => "quarto"],
    ["foto" => "fotos/quarto3.jpg", "categoria" => "quarto"],
    ["foto" => "fotos/quarto4.jpg", "categoria" => "quarto"],
    ["foto" => "fotos/quarto5.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto6.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto7.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto8.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto9.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto10.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto11.jpg", "categoria" => "quarto"],
    ["foto" => "fotos/quarto12.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto13.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto14.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto15.jpg", "categoria" => "quarto"],
    ["foto" => "fotos/quarto16.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto17.jpg", "categoria" => "quarto"],
    ["foto" => "fotos/quarto18.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto19.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto20.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto21.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto22.webp", "categoria" => "quarto"],
    ["foto" => "fotos/quarto23.jpg", "categoria" => "quarto"],
    ["foto" => "fotos/quarto24.jpg", "categoria" => "quarto"],


    ["foto" => "fotos/sala1.jpg", "categoria" => "sala"],
    ["foto" => "fotos/sala2.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala3.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala4.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala5.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala6.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala7.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala8.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala9.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala10.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala11.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala12.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala13.jpg", "categoria" => "sala"],
    ["foto" => "fotos/sala14.webp", "categoria" => "sala"],
    ["foto" => "fotos/sala15.jpg", "categoria" => "sala"],


    ["foto" => "fotos/outro1.webp", "categoria" => "outro"],
    ["foto" => "fotos/outro2.webp", "categoria" => "outro"],
    ["foto" => "fotos/outro3.webp", "categoria" => "outro"],
    ["foto" => "fotos/outro4.jpg", "categoria" => "outro"],
    ["foto" => "fotos/outro5.jpg", "categoria" => "outro"],
    ["foto" => "fotos/outro6.webp", "categoria" => "outro"],
    ["foto" => "fotos/outro7.webp", "categoria" => "outro"],
    ["foto" => "fotos/outro8.jpg", "categoria" => "outro"],
    ["foto" => "fotos/outro9.webp", "categoria" => "outro"],
    ["foto" => "fotos/outro10.jpg", "categoria" => "outro"],
    ["foto" => "fotos/outro11.webp", "categoria" => "outro"],
    ["foto" => "fotos/outro12.webp", "categoria" => "outro"],
    ["foto" => "fotos/outro13.webp", "categoria" => "outro"],
];
