<?php
    $produtos = [
        ["foto" => "fotos/cozinha-verde.jpg", "categoria" => "cozinha"],
        ["foto" => "fotos/cozinha-marrom.webp", "categoria" => "cozinha"],
        ["foto" => "fotos/cozinha-preto.jpg", "categoria" => "cozinha"],
        ["foto" => "fotos/cozinha-preto2.jpg", "categoria" => "cozinha"],
        ["foto" => "fotos/cozinha1.jpg", "categoria" => "cozinha"],
        ["foto" => "fotos/cozinha2.jpg", "categoria" => "cozinha"],
        ["foto" => "fotos/cozinha3.jpg", "categoria" => "cozinha"],
        ["foto" => "fotos/cozinha4.webp", "categoria" => "cozinha"],
        ["foto" => "fotos/cozinha5.webp", "categoria" => "cozinha"],
        ["foto" => "fotos/cozinha6.jpg", "categoria" => "cozinha"],
        ["foto" => "fotos/quarto1.jpg", "categoria" => "quarto"],
        ["foto" => "fotos/quarto2.jpg", "categoria" => "quarto"],
        ["foto" => "fotos/quarto3.jpg", "categoria" => "quarto"],
        ["foto" => "fotos/quarto4.jpg", "categoria" => "quarto"],
        ["foto" => "fotos/sala1.jpg", "categoria" => "sala"],
        ["foto" => "fotos/sala2.webp", "categoria" => "sala"],
        ["foto" => "fotos/sala3.webp", "categoria" => "sala"],
        ["foto" => "fotos/sala4.webp", "categoria" => "sala"],
        ["foto" => "fotos/sala5.webp", "categoria" => "sala"],
    ];